services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
