services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${PHX_DBPASSWORD}
      - POSTGRES_USER=${PHX_DBUSER}
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
